### CREATE
 
POST {{ host }}/api/create-or-update-clientepf
Content-Type: application/json

{
    "nome": "nomeREST",
    "sobrenome": "sobrenomeREST",
    "cpf": "11122233344",
    "token": "oneREST"
}

### UPDATE
 
POST {{ host }}/api/create-or-update-clientepf
Content-Type: application/json

{
    "id": "1669639518024",
    "nome": "updatenomeREST",
    "sobrenome": "update sobrenomeREST",
    "cpf": "11122233344",
    "token": "oneREST"
}